import { app, BrowserWindow, ipcMain } from 'electron';
import * as pty from 'node-pty';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let ptyProcess: pty.IPty | null = null;
let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 900,
    width: 1400,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open DevTools for debugging
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Terminal implementation using node-pty for proper pseudoterminal support
const startTerminal = () => {
  try {
    console.log('🚀 Starting terminal with node-pty...');
    
    // Determine the shell to use
    const shell = process.platform === 'win32' ? 'powershell.exe' : 
                  process.platform === 'darwin' ? '/bin/zsh' : '/bin/bash';
    
    console.log(`📋 Using shell: ${shell}`);
    console.log(`📂 Working directory: ${process.env.HOME || process.cwd()}`);
    
    // Create pty process with proper configuration
    ptyProcess = pty.spawn(shell, [], {
      name: 'xterm-color',
      cols: 80,
      rows: 24,
      cwd: process.env.HOME || process.cwd(),
      env: {
        ...process.env,
        TERM: 'xterm-256color',
        COLORTERM: 'truecolor',
        // Ensure PATH is properly set
        PATH: process.env.PATH,
        // Shell-specific configurations
        ...(process.platform === 'darwin' && {
          SHELL: shell,
          HOME: process.env.HOME,
          USER: process.env.USER,
          LANG: process.env.LANG || 'en_US.UTF-8'
        })
      }
    });

    console.log('✅ PTY process created successfully');
    console.log(`📏 Initial terminal size: ${ptyProcess.cols}x${ptyProcess.rows}`);

    // Handle data from terminal (output)
    ptyProcess.onData((data: string) => {
      console.log('📤 Terminal output:', JSON.stringify(data.substring(0, 100)) + (data.length > 100 ? '...' : ''));
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('terminal-data', data);
      }
    });

    // Handle terminal exit
    ptyProcess.onExit(({ exitCode, signal }) => {
      console.log(`💀 Terminal process exited with code ${exitCode}, signal ${signal}`);
      ptyProcess = null;
      
      // Restart terminal after a brief delay
      setTimeout(() => {
        console.log('🔄 Restarting terminal...');
        startTerminal();
      }, 1000);
    });

    // Send initial welcome message
    setTimeout(() => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        console.log('👋 Sending welcome message to terminal');
        mainWindow.webContents.send('terminal-data', '\r\n🎉 Terminal initialized successfully! Type commands below:\r\n');
      }
    }, 500);

  } catch (error) {
    console.error('❌ Failed to start terminal:', error);
    
    // Send error message to frontend
    setTimeout(() => {
      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('terminal-data', 
          `\r\n❌ Terminal failed to start: ${error.message}\r\n` +
          'Please check the console for more details.\r\n'
        );
      }
    }, 1000);
  }
};

// IPC handlers with improved error handling and logging
ipcMain.handle('terminal-input', (event, data: string) => {
  console.log('📥 Terminal input received:', JSON.stringify(data));
  
  if (ptyProcess) {
    try {
      ptyProcess.write(data);
      console.log('✅ Data written to PTY');
    } catch (error) {
      console.error('❌ Error writing to PTY:', error);
    }
  } else {
    console.warn('⚠️ No PTY process available for input');
    // Try to restart terminal
    startTerminal();
  }
});

ipcMain.handle('terminal-resize', (event, cols: number, rows: number) => {
  console.log(`📏 Terminal resize requested: ${cols}x${rows}`);
  
  if (ptyProcess) {
    try {
      ptyProcess.resize(cols, rows);
      console.log('✅ Terminal resized successfully');
    } catch (error) {
      console.error('❌ Error resizing terminal:', error);
    }
  } else {
    console.warn('⚠️ No PTY process available for resize');
  }
});

// MCP config handlers (unchanged)
ipcMain.handle('load-mcp-config', async () => {
  const mcpConfigPath = path.join(os.homedir(), '.config', 'claude-code', 'mcp.json');
  try {
    if (fs.existsSync(mcpConfigPath)) {
      const configData = fs.readFileSync(mcpConfigPath, 'utf-8');
      return JSON.parse(configData);
    }
  } catch (error) {
    console.error('Failed to load MCP config:', error);
  }
  return null;
});

ipcMain.handle('save-mcp-config', async (event, config: any) => {
  const mcpConfigPath = path.join(os.homedir(), '.config', 'claude-code', 'mcp.json');
  const configDir = path.dirname(mcpConfigPath);
  
  try {
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }
    fs.writeFileSync(mcpConfigPath, JSON.stringify(config, null, 2));
    return true;
  } catch (error) {
    console.error('Failed to save MCP config:', error);
    return false;
  }
});

// Start terminal when app is ready
app.on('ready', () => {
  createWindow();
  // Delay terminal start to ensure window is ready
  setTimeout(() => {
    startTerminal();
  }, 1000);
});

// Cleanup on quit
app.on('before-quit', () => {
  console.log('🛑 App quitting, cleaning up...');
  if (ptyProcess) {
    try {
      ptyProcess.kill();
      console.log('✅ PTY process terminated');
    } catch (error) {
      console.error('❌ Error terminating PTY:', error);
    }
  }
});
