import { app, BrowserWindow, ipcMain } from 'electron';
import * as pty from 'node-pty';
import * as path from 'path';
import * as fs from 'fs';
import * as os from 'os';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let ptyProcess: pty.IPty | null = null;
let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 900,
    width: 1400,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Enable DevTools for debugging
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Test node-pty directly before attempting terminal creation
const testNodePty = async () => {
  console.log('🧪 Testing node-pty module...');
  try {
    console.log('node-pty version:', require('node-pty/package.json').version);
    console.log('node-pty spawn function:', typeof pty.spawn);
    
    // Determine the best shell to use
    const shell = process.platform === 'win32' ? 'powershell.exe' : 
                  process.platform === 'darwin' ? '/bin/zsh' : '/bin/bash';
    
    console.log(`🧪 Testing PTY spawn with shell: ${shell}`);
    
    // Test with a more robust configuration
    const testPty = pty.spawn(shell, [], {
      cols: 80,
      rows: 24,
      cwd: os.homedir(),
      env: { ...process.env }
    });
    
    console.log('✅ PTY test successful, PID:', testPty.pid);
    
    // Give it a moment to initialize
    await new Promise(resolve => setTimeout(resolve, 100));
    
    testPty.kill();
    return true;
  } catch (error) {
    console.error('❌ PTY test failed:', error);
    console.error('Error details:', {
      message: error.message,
      stack: error.stack,
      code: error.code
    });
    return false;
  }
};

// Improved terminal implementation
const startTerminal = async () => {
  try {
    console.log('🚀 Starting terminal...');
    
    // First test node-pty
    const ptyTestResult = await testNodePty();
    if (!ptyTestResult) {
      throw new Error('node-pty test failed - please check console for details');
    }
    
    // Determine the best shell and args to use
    let shell: string;
    let shellArgs: string[] = [];
    
    if (process.platform === 'win32') {
      shell = 'powershell.exe';
    } else if (process.platform === 'darwin') {
      shell = '/bin/zsh';
      shellArgs = ['-l']; // Login shell to load profile
    } else {
      shell = '/bin/bash';
      shellArgs = ['-l'];
    }
    
    console.log(`🔄 Creating PTY with shell: ${shell} ${shellArgs.join(' ')}`);
    
    // Create PTY with better configuration
    ptyProcess = pty.spawn(shell, shellArgs, {
      cols: 80,
      rows: 24,
      cwd: os.homedir(),
      env: { 
        ...process.env,
        TERM: 'xterm-256color',
        COLORTERM: 'truecolor'
      }
    });

    console.log('✅ PTY process created successfully');
    console.log(`📏 Terminal size: ${ptyProcess.cols}x${ptyProcess.rows}`);
    console.log(`🆔 PTY PID: ${ptyProcess.pid}`);

    // Handle data from terminal
    ptyProcess.onData((data: string) => {
      console.log('📤 Terminal data received:', data.length, 'bytes');
      if (mainWindow && !mainWindow.isDestroyed()) {
        try {
          mainWindow.webContents.send('terminal-data', data);
        } catch (error) {
          console.error('❌ Error sending terminal data:', error);
        }
      }
    });

    // Handle terminal exit
    ptyProcess.onExit(({ exitCode, signal }) => {
      console.log(`💀 Terminal exited: code=${exitCode}, signal=${signal}`);
      ptyProcess = null;
      
      // Restart terminal after a delay
      setTimeout(() => {
        console.log('🔄 Restarting terminal...');
        startTerminal();
      }, 2000);
    });

    console.log('✅ Terminal started successfully');

  } catch (error) {
    console.error('❌ Terminal start failed:', error);
    console.error('Error details:', {
      message: error.message,
      stack: error.stack,
      code: error.code
    });
    
    // Send error to frontend
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send('terminal-data', 
        `Terminal failed: ${error.message}\nNode-pty error - please check console for details.\n`
      );
    }
  }
};

// IPC handlers
ipcMain.handle('terminal-input', (event, data: string) => {
  console.log('📥 Input:', JSON.stringify(data));
  
  if (ptyProcess) {
    try {
      ptyProcess.write(data);
    } catch (error) {
      console.error('❌ Write error:', error);
    }
  } else {
    console.warn('⚠️ No PTY for input');
  }
});

ipcMain.handle('terminal-resize', (event, cols: number, rows: number) => {
  console.log(`📏 Resize: ${cols}x${rows}`);
  
  if (ptyProcess) {
    try {
      ptyProcess.resize(cols, rows);
    } catch (error) {
      console.error('❌ Resize error:', error);
    }
  }
});

// MCP config handlers (unchanged)
ipcMain.handle('load-mcp-config', async () => {
  const mcpConfigPath = path.join(os.homedir(), '.config', 'claude-code', 'mcp.json');
  try {
    if (fs.existsSync(mcpConfigPath)) {
      const configData = fs.readFileSync(mcpConfigPath, 'utf-8');
      return JSON.parse(configData);
    }
  } catch (error) {
    console.error('Failed to load MCP config:', error);
  }
  return null;
});

ipcMain.handle('save-mcp-config', async (event, config: any) => {
  const mcpConfigPath = path.join(os.homedir(), '.config', 'claude-code', 'mcp.json');
  const configDir = path.dirname(mcpConfigPath);
  
  try {
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true });
    }
    fs.writeFileSync(mcpConfigPath, JSON.stringify(config, null, 2));
    return true;
  } catch (error) {
    console.error('Failed to save MCP config:', error);
    return false;
  }
});

// Start terminal when app is ready
app.on('ready', () => {
  createWindow();
  setTimeout(async () => {
    await startTerminal();
  }, 2000);
});

// Cleanup
app.on('before-quit', () => {
  console.log('🛑 Cleaning up...');
  if (ptyProcess) {
    try {
      ptyProcess.kill();
    } catch (error) {
      console.error('❌ Cleanup error:', error);
    }
  }
});
